version: '3'

x-variables:
  platform: &platform
    # uncomment this line when arm64 support is available (pulsar v12)
    # platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64
    platform: linux/amd64
  busybox: &busybox
    platform: linux/amd64 # busybox is not available for arm64 yet hence we force
    image: busybox:1.35.0

services:
  service:
    <<: *platform
    build:
      context: ./
    depends_on:
      - dependencies-wait
    environment:
      - PORT=3500
      - PULSAR_ENDPOINT=pulsar://pulsar:6650
    ports:
      - ${PORT:-3500}:3500
    volumes:
      - ./src:/home/user/src:ro

  pulsar:
    # <<: *platform # uncomment this line when arm64 support is available (v12)
    platform: linux/amd64 # remove this hard coded line when arm64 support is available (v12)
    image: apachepulsar/pulsar:2.11.3
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: |
      /bin/bash -c "
        bin/apply-config-from-env.py conf/standalone.conf && \
        bin/pulsar standalone
      "
    healthcheck:
      interval: 1s
      retries: 120
      start_period: 5s
      test: ./bin/pulsar-admin brokers healthcheck
    ports:
      - 3501:8080
      - 6650:6650
    user: root
    volumes:
      - pulsar-data:/pulsar/config
      - pulsar-data:/pulsar/data

  pulsar-wait:
    <<: *busybox
    depends_on:
      pulsar:
        condition: service_healthy

  dependencies-wait:
    <<: *busybox
    depends_on:
      - pulsar-wait

volumes:
  pulsar-data:
    driver: local
